# Generated by Django 2.0.4 on 2018-04-14 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=200)),
                ('image_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=200)),
                ('instance_name', models.CharField(max_length=200)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='awsapp.Image')),
            ],
        ),
    ]
